"""
Report Generator for LLM Response Quality Evaluation.
"""

import os
import json
import pandas as pd
from typing import List, Dict, Any
from evaluator.schema import EvaluationResult


class ReportGenerator:
    """Generates Markdown reports, JSON metric summaries, and CSV results."""

    @staticmethod
    def generate_markdown_report(metrics: Dict[str, Any], output_path: str) -> str:
        os.makedirs(os.path.dirname(output_path), exist_ok=True)

        total = metrics.get("total_evaluated", 0)
        passed = metrics.get("passed_count", 0)
        failed = metrics.get("failed_count", 0)
        pass_rate = metrics.get("pass_rate", 0.0) * 100
        mean_score = metrics.get("overall_mean_score", 0.0)
        std_score = metrics.get("overall_std_dev", 0.0)

        dim_rows = []
        for dim, stats in metrics.get("dimension_metrics", {}).items():
            dim_rows.append(
                f"| `{dim}` | {stats['mean_score']:.4f} | {stats['std_dev']:.4f} | {stats['pass_rate']*100:.1f}% | {stats['min_score']:.2f} | {stats['max_score']:.2f} |"
            )
        dim_table = "\n".join(dim_rows) if dim_rows else "| N/A | N/A | N/A | N/A | N/A | N/A |"

        err_rows = []
        for err, stats in metrics.get("error_distribution", {}).items():
            err_rows.append(f"| `{err}` | {stats['count']} | {stats['percentage']:.1f}% |")
        err_table = "\n".join(err_rows) if err_rows else "| None | 0 | 0.0% |"

        fail_rows = []
        for f in metrics.get("failures", [])[:10]:
            fail_rows.append(
                f"| `{f['id']}` | `{f['primary_error']}` | `{f['max_severity']}` | {f['score']:.4f} | {f['prompt'][:50]}... |"
            )
        fail_table = "\n".join(fail_rows) if fail_rows else "| None | N/A | N/A | N/A | No failures recorded |"

        content = f"""# LLM Response Quality Evaluation Report

## Executive Summary

- **Total Evaluated Examples**: `{total}`
- **Passed Quality Gate (Score >= 0.70 & No Critical/High Errors)**: `{passed}` (`{pass_rate:.1f}%`)
- **Failed Quality Gate**: `{failed}` (`{100 - pass_rate:.1f}%`)
- **Overall Mean Quality Score**: `{mean_score:.4f}` ± `{std_score:.4f}`

---

## Quality Score Breakdown by Dimension

| Dimension | Mean Score | Std Dev | Pass Rate | Min Score | Max Score |
| :--- | :--- | :--- | :--- | :--- | :--- |
{dim_table}

---

## Error Taxonomy Frequency & Distribution

| Error Category | Count | Percentage |
| :--- | :--- | :--- |
{err_table}

---

## Failure Analysis (Top Failing Examples)

| Sample ID | Primary Error | Max Severity | Score | Prompt Snippet |
| :--- | :--- | :--- | :--- | :--- |
{fail_table}

---

## Visualizations

- Dimension Mean Scores: `reports/figures/dimension_scores.png`
- Error Taxonomy Distribution: `reports/figures/error_taxonomy.png`
- Error Severity Breakdown: `reports/figures/severity_distribution.png`

---
*Report auto-generated by LLM Response Quality Evaluator v1.0.0*
"""

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)

        return content

    @staticmethod
    def export_results(results: List[EvaluationResult], output_dir: str):
        os.makedirs(output_dir, exist_ok=True)

        # Export raw JSONL
        json_path = os.path.join(output_dir, "evaluation_results.json")
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump([r.to_dict() for r in results], f, indent=2)

        # Export summary CSV
        csv_rows = []
        for r in results:
            csv_rows.append({
                "id": r.id,
                "overall_score": r.overall_score,
                "passed": r.passed,
                "max_severity": r.max_severity.value,
                "primary_error": r.primary_error.value if r.primary_error else "none",
                "prompt": r.prompt,
                "response": r.response,
                "reference_answer": r.reference_answer or ""
            })

        df = pd.DataFrame(csv_rows)
        csv_path = os.path.join(output_dir, "evaluation_results.csv")
        df.to_csv(csv_path, index=False)
